language: ruby
sudo: false
cache:
  - bundler
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
before_install: gem install bundler -v 1.10.6

env:
  matrix:
    - RAILS_VERSION="~> 4.2"
    - RAILS_VERSION="~> 5.0.0"
